# MACROPAD Hotkeys example: Minecraft Effects (Creative) for Bedrock Edition

# NOTE: There appears to be a line length limit. Exceeding that limit appears
#       to result in silent failure.  Therefore, the key sequences are split
#       across multiple lines.

from adafruit_hid.keycode import Keycode # REQUIRED if using Keycode.* values

# See https://minecraft.fandom.com/wiki/Effect

# Unfortunately, bedrock edition has no single command that both
# gives an item and enchants it.  Thus, have to place the item in
# the player's inventory slot, enchant it, then equip it.

from adafruit_hid.keycode import Keycode # REQUIRED if using Keycode.* values

DELAY_AFTER_ESCAPE = 0.05
DELAY_AFTER_COMMAND = 0.10

app = {
    'name': 'Minecraft PE (equip)',
    'macros': [
        (0x003000, 'helm', [
            Keycode.ESCAPE, -Keycode.ESCAPE, DELAY_AFTER_ESCAPE,
            '/replaceitem entity @s slot.weapon.mainhand 0 destroy netherite_helmet',
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s mending 1',
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s protection 4',
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s respiration 3',
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s aqua_affinity 1',
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s unbreaking 3',
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            Keycode.ESCAPE, -Keycode.ESCAPE, DELAY_AFTER_ESCAPE,
            'E']),
        (12288, 'plate', [
            Keycode.ESCAPE, -Keycode.ESCAPE, DELAY_AFTER_ESCAPE,
            '/replaceitem entity @s slot.weapon.mainhand 0 destroy netherite_chestplate', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s mending 1',
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s protection 4',
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s unbreaking 3', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            Keycode.ESCAPE, -Keycode.ESCAPE, DELAY_AFTER_ESCAPE,
            'E']),
        (12288, 'legs', [
            Keycode.ESCAPE, -Keycode.ESCAPE, DELAY_AFTER_ESCAPE,
            '/replaceitem entity @s slot.weapon.mainhand 0 destroy netherite_leggings', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s mending 1', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s protection 4', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s unbreaking 3', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            Keycode.ESCAPE, -Keycode.ESCAPE, DELAY_AFTER_ESCAPE,
            'E']),
        (12288, 'boots', [
            Keycode.ESCAPE, -Keycode.ESCAPE, DELAY_AFTER_ESCAPE,
            '/replaceitem entity @s slot.weapon.mainhand 0 destroy netherite_boots', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s mending 1', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s protection 4', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s feather_falling 4', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s depth_strider 3', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s soul_speed 3', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s unbreaking 3', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            Keycode.ESCAPE, -Keycode.ESCAPE, DELAY_AFTER_ESCAPE,
            'E']),
        (12288, 'frosty', [
            Keycode.ESCAPE, -Keycode.ESCAPE, DELAY_AFTER_ESCAPE,
            '/replaceitem entity @s slot.weapon.mainhand 0 destroy netherite_boots', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s mending 1', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s protection 4', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s feather_falling 4', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s frost_walker 2', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s soul_speed 3', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s unbreaking 3', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            Keycode.ESCAPE, -Keycode.ESCAPE, DELAY_AFTER_ESCAPE,
            'E']),
        (3145728, 'feedme', [
            Keycode.ESCAPE, -Keycode.ESCAPE, DELAY_AFTER_ESCAPE,
            '/replaceitem entity @s slot.weapon.mainhand 0 destroy netherite_sword', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s mending 1', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s fire_aspect 2', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s knockback 2', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s looting 3', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s sharpness 5', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s unbreaking 3', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            Keycode.ESCAPE, -Keycode.ESCAPE, DELAY_AFTER_ESCAPE,
            Keycode.PAGE_UP, -Keycode.PAGE_UP]),
        (3145728, 'excal', [
            Keycode.ESCAPE, -Keycode.ESCAPE, DELAY_AFTER_ESCAPE,
            '/replaceitem entity @s slot.weapon.mainhand 0 destroy netherite_sword', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s mending 1', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s fire_aspect 2', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s knockback 2', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s looting 3', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s sharpness 5', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s unbreaking 3', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            Keycode.ESCAPE, -Keycode.ESCAPE, DELAY_AFTER_ESCAPE,
            Keycode.PAGE_UP, -Keycode.PAGE_UP]),
        (3145728, 'trident', [
            Keycode.ESCAPE, -Keycode.ESCAPE, DELAY_AFTER_ESCAPE,
            '/replaceitem entity @s slot.weapon.mainhand 0 destroy trident', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s mending 1', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s loyalty 3', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s channeling 1', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s riptide 3', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s impaling 5', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s unbreaking 3', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            Keycode.ESCAPE, -Keycode.ESCAPE, DELAY_AFTER_ESCAPE,
            Keycode.PAGE_UP, -Keycode.PAGE_UP]),
        (3145728, 'bow', [
            Keycode.ESCAPE, -Keycode.ESCAPE, DELAY_AFTER_ESCAPE,
            '/replaceitem entity @s slot.weapon.mainhand 0 destroy bow', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s mending 1', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s power 5', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s punch 2', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s unbreaking 3', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            Keycode.ESCAPE, -Keycode.ESCAPE, DELAY_AFTER_ESCAPE,
            Keycode.PAGE_UP, -Keycode.PAGE_UP]),
        (48, 'silky', [
            Keycode.ESCAPE, -Keycode.ESCAPE, DELAY_AFTER_ESCAPE,
            '/replaceitem entity @s slot.weapon.mainhand 0 destroy netherite_pickaxe', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s mending 1', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s efficiency 5', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s silk_touch 1', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s unbreaking 3', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            Keycode.ESCAPE, -Keycode.ESCAPE, DELAY_AFTER_ESCAPE,
            Keycode.PAGE_UP, -Keycode.PAGE_UP]),
        (48, 'pickme', [
            Keycode.ESCAPE, -Keycode.ESCAPE, DELAY_AFTER_ESCAPE,
            '/replaceitem entity @s slot.weapon.mainhand 0 destroy netherite_pickaxe', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s mending 1', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s efficiency 5', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s fortune 3', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s unbreaking 3', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            Keycode.ESCAPE, -Keycode.ESCAPE, DELAY_AFTER_ESCAPE,
            Keycode.PAGE_UP, -Keycode.PAGE_UP]),
        (48, 'axe', [
            Keycode.ESCAPE, -Keycode.ESCAPE, DELAY_AFTER_ESCAPE,
            '/replaceitem entity @s slot.weapon.mainhand 0 destroy netherite_axe',
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s mending 1', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s fortune 3', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s efficiency 5', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s sharpness 5', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            '/enchant @s unbreaking 3', 
            Keycode.RETURN, -Keycode.RETURN, DELAY_AFTER_COMMAND,
            Keycode.ESCAPE, -Keycode.ESCAPE, DELAY_AFTER_ESCAPE,
            Keycode.PAGE_UP, -Keycode.PAGE_UP]),
    ]
}
