# SPDX-FileCopyrightText: 2026 Pedro Ruiz for Adafruit Industries
#
# SPDX-License-Identifier: MIT
"""
Minecraft Compass — boot.py

Decides who can write to the CIRCUITPY filesystem this session, and
handles any pending calibration write queued by code.py.

Write access can only belong to ONE side at a time (the host computer or
the running code), so this file picks based on whether the D5 side button
is held during power-up:

- D5 held at boot  -> COMPUTER edit mode. The filesystem stays in its
  default state (host computer can write; code.py cannot). Use this to
  edit code.py or hand-add waypoints to waypoints.json from a text editor
  (paste coordinates straight from Google Maps).

- D5 not held (normal boot) -> DEVICE mode. The filesystem is remounted
  writable for code.py so it can save waypoints to waypoints.json in the
  field. The host computer sees CIRCUITPY as read-only until the next
  boot without the button held.

Calibration still uses the NVM flow (unchanged): code.py sets NVM flags
and soft-resets, and the pending action is applied here. That works in
either mode because this file remounts writable when an action is queued.

NVM layout (microcontroller.nvm):
- Byte 0: Remount flag. 1 = a calibration action is pending this boot.
- Byte 1: Pending action.
            0 = no action
            1 = write calibration data from NVM to settings.toml
            2 = clear the MAG_ calibration keys to force recalibration
- Bytes 2-29: 28 bytes of calibration data (seven 32-bit big-endian
              floats): offset_x, offset_y, offset_z, scale_x, scale_y,
              scale_z, heading_offset
- Byte 30: theme index (managed by code.py, not used here)
"""
import struct
import board
import digitalio
import storage
import microcontroller

ACTION_NONE = 0
ACTION_WRITE_CALIBRATION = 1
ACTION_CLEAR_CALIBRATION = 2

# Read the D5 side button. It is wired active-low with an internal pull-up,
# so a held button reads False. Released (normal boot) reads True.
button = digitalio.DigitalInOut(board.D5)
button.direction = digitalio.Direction.INPUT
button.pull = digitalio.Pull.UP
computer_edit_mode = not button.value  # held == edit from computer
button.deinit()

if computer_edit_mode:
    # Leave the default mount (host computer keeps write access). code.py
    # cannot save in this mode, which is fine while editing from a desktop.
    print("boot.py: COMPUTER edit mode (D5 held) - host can write CIRCUITPY")
else:
    # Device mode: code.py gets write access so it can save waypoints.
    storage.remount("/", readonly=False)
    print("boot.py: DEVICE mode - code.py can write CIRCUITPY (host read-only)")

# Apply any pending calibration action regardless of mode. The remount
# above (device mode) already gave write access; in computer-edit mode a
# calibration action is unlikely, but remount here too so it still works.
if microcontroller.nvm[0] == 1:
    if computer_edit_mode:
        storage.remount("/", readonly=False)

    action = microcontroller.nvm[1]
    if action == ACTION_WRITE_CALIBRATION:
        raw = bytes(microcontroller.nvm[2:30])
        (
            offset_x, offset_y, offset_z,
            scale_x, scale_y, scale_z,
            heading_offset,
        ) = struct.unpack(">fffffff", raw)
        with open("/settings.toml", "w", encoding="utf-8") as f:
            f.write("# Magnetometer calibration — auto-generated by calibration.py\n")
            f.write(f'MAG_OFFSET_X = "{offset_x:+0.4f}"\n')
            f.write(f'MAG_OFFSET_Y = "{offset_y:+0.4f}"\n')
            f.write(f'MAG_OFFSET_Z = "{offset_z:+0.4f}"\n')
            f.write(f'MAG_SCALE_X = "{scale_x:0.4f}"\n')
            f.write(f'MAG_SCALE_Y = "{scale_y:0.4f}"\n')
            f.write(f'MAG_SCALE_Z = "{scale_z:0.4f}"\n')
            f.write(f'MAG_HEADING_OFFSET = "{heading_offset:0.4f}"\n')
        microcontroller.nvm[1] = ACTION_NONE

    elif action == ACTION_CLEAR_CALIBRATION:
        # Remove only the calibration keys this project owns, preserving any
        # other entries a user may have added to settings.toml. With the MAG_
        # lines gone, code.py sees no calibration and hands off to
        # calibration.py on the next boot.
        try:
            with open("/settings.toml", "r", encoding="utf-8") as f:
                kept = [line for line in f if not line.startswith("MAG_")]
            with open("/settings.toml", "w", encoding="utf-8") as f:
                f.write("".join(kept))
        except OSError:
            pass   # no file yet, or read-only: nothing to clear
        microcontroller.nvm[1] = ACTION_NONE

    microcontroller.nvm[0] = 0
